--1
UPDATE PACIENTE P SET p.PESO = 8.5
WHERE p.ID_PACIENTE = 1

SELECT * FROM PACIENTE p 

--2
UPDATE MEDICAMENTOS M SET m.ESTOQUE = 50
WHERE m.ID_MEDICAMENTO = 3

SELECT * FROM MEDICAMENTOS m 

--3
UPDATE TUTOR t SET t.DATA_NASCIMENTO = '2001/05/15'
WHERE t.ID_TUTOR = 2

SELECT * FROM TUTOR t 

--4
UPDATE AGENDAMENTO a SET a.MOTIVO = 'Dor de barriga severa'
WHERE a.ID_AGENDAMENTO = 5

SELECT * FROM AGENDAMENTO a 

--5
UPDATE MEDICAMENTOS m SET m.DESCRICAO =  'Anti-inflamatório para articulações'
WHERE m.ID_MEDICAMENTO = 6

SELECT * FROM MEDICAMENTOS m 

--6
UPDATE TUTOR t SET t.NOME = 'Maria Oliveira'
WHERE t.ID_TUTOR = 3

SELECT * FROM TUTOR t 

--7
UPDATE MEDICAMENTOS m SET m.DESCRICAO =  'Aplicar no olho afetado a cada 4 horas'
WHERE m.ID_MEDICAMENTO = 2

SELECT * FROM MEDICAMENTOS m 

--8
UPDATE TUTOR t SET t.ENDERECO = 'Rua dos Girassóis, 123'
WHERE t.ID_TUTOR = 4

SELECT * FROM TUTOR t 

--9
DELETE FROM AGENDAMENTO a
WHERE a.id_agendamento = 7

SELECT * FROM AGENDAMENTO a 

--10
DELETE FROM MEDICAMENTOS m
WHERE m.id_medicamento = 8

SELECT * FROM MEDICAMENTOS m 

--11
DELETE FROM RECEITA r 
  WHERE r.ID_AGENDAMENTO in (SELECT a.ID_AGENDAMENTO 
                              FROM AGENDAMENTO a 
  							 WHERE a.ID_PACIENTE in (SELECT p.ID_PACIENTE 
  						   							 FROM PACIENTE p
 						                            WHERE p.ID_TUTOR = 5));
 
 DELETE FROM AGENDAMENTO a 
  WHERE a.ID_PACIENTE in (SELECT p.ID_PACIENTE 
  						   FROM PACIENTE p
 						  WHERE p.ID_TUTOR = 5);

DELETE FROM paciente p
 WHERE p.ID_TUTOR = 5;

SELECT * FROM RECEITA r 

--12
DELETE FROM RECEITA
WHERE ID_AGENDAMENTO IS NULL

SELECT * FROM RECEITA r 

--13
DELETE FROM TUTOR t
WHERE t.data_nascimento < '1987-01-01'

SELECT * FROM TUTOR t 

--14
DELETE FROM ITENSRECEITA
WHERE ID_RECEITA BETWEEN 7 AND 9

SELECT * FROM ITENSRECEITA i 





